language: objective-c
before_script:
  - export LANG=en_US.UTF-8
  - gem i cocoapods --no-ri --no-rdoc
  - cd Bootstrap; pod install ; cd ..
xcode_workspace: Bootstrap/ARAnalyticsTests.xcworkspace
xcode_scheme: ARAnalyticsBootstrapiOS
xcode_sdk: iphonesimulator
