language: objective-c
osx_image: xcode8.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - gem install cocoapods --no-document --pre --quiet
  - bundle exec danger
  - cd Example; pod update ; cd ..

script:
  - xctool -workspace Example/ARAnalyticsTests.xcworkspace -scheme ARAnalyticsBootstrapiOS -sdk iphonesimulator run-tests
